# =============================================================================
# Module: ml_optimizer.py
# Purpose: PATENT INNOVATION #4 — ML-Based Filter Weight Optimization
#
# Instead of predicting a single "best filter", this module trains a
# multi-output regression model that predicts OPTIMAL BLEND WEIGHTS
# for the multi-filter fusion engine:
#
#   final_image = w1 * gaussian + w2 * median + w3 * bilateral
#
# The model learns from synthetic training data generated by:
#   1. Injecting different noise types/levels into a reference image
#   2. Applying all three filters
#   3. Grid-searching weight combinations to find the PSNR-optimal blend
#   4. Recording (features → optimal_weights) as training pairs
#
# Feature vector (12 dimensions):
#   [noise_intensity, sp_ratio, laplacian_var, hist_kurtosis,
#    mean_local_var, edge_density, image_mean, image_std,
#    gaussian_psnr, median_psnr, bilateral_psnr, noise_type_encoded]
#
# Also retains a legacy classifier for "best single filter" recommendation.
# =============================================================================

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from .utils import add_gaussian_noise, add_salt_pepper_noise, add_mixed_noise
from .filters import apply_gaussian, apply_median, apply_bilateral
from .fusion import weighted_filter_fusion
from .metrics import compute_psnr
from .noise_detection import compute_noise_features


# ── Feature Extraction ───────────────────────────────────────────────────────

def extract_ml_features(
    noisy_image: np.ndarray,
    noise_profile: dict,
    gaussian_psnr: float,
    median_psnr: float,
    bilateral_psnr: float,
) -> np.ndarray:
    """
    Build a 12-dimension feature vector for the ML weight predictor.

    Features combine noise characteristics, image statistics, and
    individual filter performance — giving the model enough information
    to predict how to blend the filters optimally.
    """
    feats = noise_profile.get("features", {})

    # Encode noise type as numeric
    noise_type_map = {"gaussian": 0, "impulse": 1, "mixed": 2}
    noise_type_code = noise_type_map.get(noise_profile.get("noise_type", "gaussian"), 0)

    return np.array([
        noise_profile.get("noise_intensity", 0.5),
        feats.get("salt_pepper_ratio", 0.0),
        feats.get("laplacian_variance", 0.0),
        feats.get("histogram_kurtosis", 0.0),
        feats.get("mean_local_variance", 0.0),
        feats.get("edge_density", 0.0),
        feats.get("image_mean", 128.0),
        feats.get("global_std", 50.0),
        gaussian_psnr,
        median_psnr,
        bilateral_psnr,
        float(noise_type_code),
    ], dtype=np.float64)


# ── Grid Search for Optimal Weights ──────────────────────────────────────────

def _grid_search_weights(
    reference: np.ndarray,
    gaussian_img: np.ndarray,
    median_img: np.ndarray,
    bilateral_img: np.ndarray,
    step: float = 0.1,
) -> tuple[np.ndarray, float]:
    """
    Exhaustively search weight combinations [w1, w2, w3] with w1+w2+w3=1
    to find the blend that maximises PSNR against the reference image.

    Returns (best_weights, best_psnr).
    """
    best_psnr = -1.0
    best_w = np.array([1.0 / 3, 1.0 / 3, 1.0 / 3])

    steps = np.arange(0.0, 1.0 + step / 2, step)
    for w1 in steps:
        for w2 in steps:
            w3 = 1.0 - w1 - w2
            if w3 < -0.01:
                continue
            w3 = max(w3, 0.0)
            fused = weighted_filter_fusion(gaussian_img, median_img, bilateral_img, [w1, w2, w3])
            psnr = compute_psnr(reference, fused)
            if psnr > best_psnr:
                best_psnr = psnr
                best_w = np.array([w1, w2, w3])

    return best_w, best_psnr


# ── Training Data Generation ─────────────────────────────────────────────────

def build_weight_training_data(
    reference: np.ndarray,
    filter_params: dict,
) -> tuple[np.ndarray, np.ndarray]:
    """
    ┌─────────────────────────────────────────────────────────────────────┐
    │  Generate synthetic training data for the weight predictor.        │
    │                                                                     │
    │  For ~12 noise configurations (varying type and intensity):        │
    │    1. Inject noise into the reference image                        │
    │    2. Apply all 3 filters                                          │
    │    3. Grid-search optimal weights (maximise PSNR)                  │
    │    4. Extract 12-dim feature vector                                │
    │    5. Store (features → optimal_weights)                           │
    └─────────────────────────────────────────────────────────────────────┘
    """
    from .noise_detection import detect_noise_profile

    g_ksize = filter_params.get("g_ksize", 5)
    g_sigma = filter_params.get("g_sigma", 1.5)
    m_ksize = filter_params.get("m_ksize", 5)
    b_d = filter_params.get("b_d", 9)
    b_sc = filter_params.get("b_sc", 75)
    b_ss = filter_params.get("b_ss", 75)

    X_list, Y_list = [], []

    # ── Gaussian noise at multiple levels ─────────────────────────────────
    for sigma in [10, 20, 30, 45, 60]:
        noisy = add_gaussian_noise(reference, sigma)
        _add_sample(reference, noisy, g_ksize, g_sigma, m_ksize, b_d, b_sc, b_ss, X_list, Y_list)

    # ── Salt & pepper noise at multiple levels ────────────────────────────
    for amount in [0.02, 0.05, 0.10, 0.15]:
        noisy = add_salt_pepper_noise(reference, amount)
        _add_sample(reference, noisy, g_ksize, g_sigma, m_ksize, b_d, b_sc, b_ss, X_list, Y_list)

    # ── Mixed noise ───────────────────────────────────────────────────────
    for sigma, amount in [(15, 0.03), (30, 0.05), (45, 0.08)]:
        noisy = add_mixed_noise(reference, sigma, amount)
        _add_sample(reference, noisy, g_ksize, g_sigma, m_ksize, b_d, b_sc, b_ss, X_list, Y_list)

    return np.array(X_list, dtype=np.float64), np.array(Y_list, dtype=np.float64)


def _add_sample(reference, noisy, g_ksize, g_sigma, m_ksize, b_d, b_sc, b_ss, X_list, Y_list):
    """Helper: process one noisy image and append to training lists."""
    from .noise_detection import detect_noise_profile

    g_img = apply_gaussian(noisy, g_ksize, g_sigma)
    m_img = apply_median(noisy, m_ksize)
    b_img = apply_bilateral(noisy, b_d, b_sc, b_ss)

    g_psnr = compute_psnr(reference, g_img)
    m_psnr = compute_psnr(reference, m_img)
    b_psnr = compute_psnr(reference, b_img)

    noise_profile = detect_noise_profile(noisy)
    features = extract_ml_features(noisy, noise_profile, g_psnr, m_psnr, b_psnr)

    best_w, _ = _grid_search_weights(reference, g_img, m_img, b_img, step=0.1)

    X_list.append(features)
    Y_list.append(best_w)


# ── Model Training ────────────────────────────────────────────────────────────

def train_weight_predictor(
    X: np.ndarray, Y: np.ndarray,
) -> tuple:
    """
    Train a multi-output Ridge regressor to predict 3 filter weights
    from the 12-dim feature vector.

    Returns (model, scaler).
    """
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = MultiOutputRegressor(Ridge(alpha=1.0))
    model.fit(X_scaled, Y)

    return model, scaler


def predict_filter_weights(
    model, scaler: StandardScaler, features: np.ndarray,
) -> np.ndarray:
    """
    ┌─────────────────────────────────────────────────────────────────────┐
    │  PATENT INNOVATION: ML-Based Filter Weight Prediction              │
    │                                                                     │
    │  Given a 12-dim feature vector, predict optimal blend weights      │
    │  [w_gaussian, w_median, w_bilateral] for the fusion engine.        │
    │                                                                     │
    │  Weights are clipped to [0, 1] and normalised to sum to 1.0.      │
    └─────────────────────────────────────────────────────────────────────┘
    """
    feat = features.reshape(1, -1) if features.ndim == 1 else features
    scaled = scaler.transform(feat)
    raw_weights = model.predict(scaled)[0]

    # Clip and normalise
    w = np.clip(raw_weights, 0.0, 1.0)
    w_sum = w.sum()
    if w_sum > 0:
        w = w / w_sum
    else:
        w = np.array([1.0 / 3, 1.0 / 3, 1.0 / 3])

    return w


# ── Legacy: Single Best Filter Classifier ────────────────────────────────────

def build_classifier_training_data(
    reference: np.ndarray,
    filter_params: dict,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Build training data for the legacy single-best-filter classifier.
    Labels: 0=Gaussian, 1=Median, 2=Bilateral (highest PSNR wins).
    Features: 5-dim [PSNR, MSE, SSIM, mean, std] from the noisy image.
    """
    from .metrics import compute_basic_metrics
    X, y = [], []
    for sigma in np.linspace(5, 60, 8):
        noisy = add_gaussian_noise(reference, sigma)
        g_img = apply_gaussian(noisy, filter_params["g_ksize"], filter_params["g_sigma"])
        m_img = apply_median(noisy, filter_params["m_ksize"])
        b_img = apply_bilateral(noisy, filter_params["b_d"], filter_params["b_sc"], filter_params["b_ss"])

        psnr_scores = [
            compute_psnr(reference, g_img),
            compute_psnr(reference, m_img),
            compute_psnr(reference, b_img),
        ]
        best_label = int(np.argmax(psnr_scores))

        noisy_metrics = compute_basic_metrics(reference, noisy)
        feat = [
            noisy_metrics["PSNR"], noisy_metrics["MSE"], noisy_metrics["SSIM"],
            float(np.mean(noisy)), float(np.std(noisy)),
        ]
        X.append(feat)
        y.append(best_label)

    return np.array(X, dtype=np.float32), np.array(y, dtype=np.int32)


def train_classifier(X: np.ndarray, y: np.ndarray, model_type: str = "KNN"):
    """Train KNN or SVM classifier for single-best-filter prediction."""
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    if model_type == "KNN":
        clf = KNeighborsClassifier(n_neighbors=3)
    else:
        clf = SVC(kernel="rbf", C=10, gamma="scale")
    clf.fit(X_scaled, y)
    return clf, scaler


def predict_best_filter(clf, scaler, noisy_image, noisy_metrics, filter_names):
    """Predict the single best filter using the legacy classifier."""
    feat = np.array([[
        noisy_metrics["PSNR"], noisy_metrics["MSE"], noisy_metrics["SSIM"],
        float(np.mean(noisy_image)), float(np.std(noisy_image)),
    ]], dtype=np.float32)
    scaled = scaler.transform(feat)
    label = int(clf.predict(scaled)[0])
    if 0 <= label < len(filter_names):
        return filter_names[label]
    # Fallback
    return filter_names[0]
